# Generated by Django 3.1 on 2020-09-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='excerpt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
