# Generated by Django 3.1 on 2020-09-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200919_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
