# Generated by Django 3.1 on 2020-10-13 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20201013_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 13, 17, 30, 59, 714235, tzinfo=utc)),
        ),
    ]
